# Laboratorio No.2 Redes Neuronales

## Andrés Urízar - 17632

In [1]:
import mnist_reader
import numpy as np
#import pandas as pd
from scipy import optimize as op
from functools import reduce
X_train, y_train = mnist_reader.load_mnist('data/fashion', kind='train')
X_test, y_test = mnist_reader.load_mnist('data/fashion', kind='t10k')
#data = pd.read_csv('fashion-mnist_train.csv')

### Se procesa la información

In [2]:
X = X_train[:, 1:]/1000.0  #Normalizacion de los datos
#X = data.iloc[:, 1:]/1000.0
m,n = X.shape
y = np.asarray(y_train)
y = y.reshape(m,1)
Y = (y == np.array(range(10))).astype(int)

In [3]:
X[3,0:10]

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.033, 0.096,
       0.175])

In [4]:
Y.shape

(60000, 10)

### Se comienzan a realizar las funciones

#### Función para dar forma a las matrices

In [5]:
flatten_list_of_arrays = lambda list_of_arrays: reduce(
    lambda acc, v: np.array([*acc.flatten(), *v.flatten()]),
    list_of_arrays
)    

In [6]:
def inflate_matrixes(flat_thetas, shapes):
    layers = len(shapes)+1
    sizes = [shape[0]*shape[1] for shape in shapes]
    steps = np.zeros(layers, dtype=int)
    
    for i in range(layers-1):
        steps[i+1]=steps[i]+sizes[i]
        
    return[
        flat_thetas[steps[i]: steps[i+1]].reshape(*shapes[i])
        for i in range(layers-1)
    ]

In [24]:
sigmoid = lambda z: 1.0/(1.0+np.exp(-z))

In [25]:
#Forward propagation (lista de thetas, X=matrix(60000,784))
def feed_propagation(thetas, X):
    list_of_a = [X] #Se guarda en la primera posicion el input en este caso X
    for i in range(len(thetas)):
        temp = np.hstack((np.ones(len(X)).reshape(len(X),1),
          list_of_a[i]      
        ))
        list_of_a.append(
            sigmoid(
                np.matmul(
                    temp,
                    thetas[i].T
                )
            )
        )
    return list_of_a

### Se realiza la arquitectura de las matrices de la red neuronal

In [26]:
REDES = np.array([
        n,
        125,
        10
    ])

theta_shapes = np.hstack((
    REDES[1:].reshape(len(REDES)-1, 1),
    (REDES[:-1]+1).reshape(len(REDES)-1,1)
))


flat_thetas = flatten_list_of_arrays([
    np.random.rand(*theta_shape) 
    for theta_shape in theta_shapes
])

In [27]:
theta_shapes

array([[125, 784],
       [ 10, 126]])

In [28]:
m, layers = len(X), len(theta_shapes)+1

In [29]:
thetas = inflate_matrixes(flat_thetas,theta_shapes)
thetas[0].shape

(125, 784)

In [30]:
a = feed_propagation(thetas, X)

In [32]:
a

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
         1.        ],
        [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
         1.        ],
        [0.99999961, 0.99999963, 0.99999985, ..., 0.99999933, 0.99999982,
         0.99999968],
        ...,
        [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
         1.        ],
        [0.99999997, 0.99999997, 0.99999999, ..., 0.99999993, 0.99999997,
         0.99999998],
        [0.99992524, 0.99991374, 0.9999575 , ..., 0.99974337, 0.99993039,
         0.99994438]]),
 array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 